name: my-lando-app
recipe: drupal11
config:
  php: "8.3"
  via: apache:2.4
  database: mysql:8.0
  composer_version: 2-latest
  drush: ^13
  webroot: web
services:
appserver:
  build_as_root:
    - curl -sL https://deb.nodesource.com/setup_16.x | bash -
    - apt-get install -qq -y nodejs
    - chown -R www-data /usr/lib/node_modules
    - chown -R www-data /usr/bin
    - npm install --silent -g npm
  run_as_root:
    - "a2enmod headers"
    - "service apache2 reload"
  overrides:
    ports:
      - 6006:6006
      - 6007:6007
tooling:
node:
  service: appserver
npm:
  service: appserver
npx:
  service: appserver
yarn:
  service: appserver